FIRST_NAME = "JETHALAL"
MIDDLE_NAME = "CHAMPAKLAL"
LAST_NAME = "GADA"
FULL_NAME_1 = "JETHALAL " "CHAMPAKLAL " "GADA"
FULL_NAME_2 = "JETHALAL " + "CHAMPAKLAL " + "GADA"
FULL_NAME_3 = FIRST_NAME + " " + MIDDLE_NAME + " " + LAST_NAME
FULL_NAME_4 = F"{FIRST_NAME} {2+5} {MIDDLE_NAME} {LAST_NAME}"
FULL_NAME_5 = f"{FIRST_NAME} {MIDDLE_NAME} {LAST_NAME}"

print(FULL_NAME_1)
print(FULL_NAME_2)
print(FULL_NAME_3)
print(FULL_NAME_4)
print(FULL_NAME_5)
